### ISSUE TITLE
Projects referencing Nuget v1.0.2 doesn't compile with MediatR nuget package 8.1.0

### ISSUE THREAD

**Issue by kyletindle** [AustinDavies/MediatR.Behaviors.Authorization#1]
The sample classes in the wiki complain and look for v8.0.1 of MediatR and not the latest version although dependencies say >=8.0.1

**Comment by AustinDavies** [comment]
I updated the package references. Let me know if v1.0.3 works.

**Comment by AustinDavies** [comment]
> The sample classes in the wiki complain and look for v8.0.1 of MediatR and not the latest version although dependencies say >=8.0.1

I updated the package references. Let me know if v1.0.3 works.

**Comment by AustinDavies** [comment]
> The sample classes in the wiki complain and look for v8.0.1 of MediatR and not the latest version although dependencies say >=8.0.1

I updated the package references. Let me know if v1.1.0 works.
