### ISSUE TITLE
Support for void request handlers

### ISSUE THREAD

**Issue by alandecastros** [AustinDavies/MediatR.Behaviors.Authorization#12]
Hi, 

I was trying to use the lib and the handlers weren't being called using mediatr's void request handlers. 
I think the problem is `where TRequest : IRequest<TResponse>` on the `RequestAuthorizationBehavior.cs`. I don't think it's necessary anymore.

Regards

**Comment by AustinDavies** [comment]
Thanks @alandecastros for bringing this issue up. I will fix this issue promptly.
