### ISSUE TITLE
Create Unit Tests

### ISSUE THREAD

**Issue by AustinDavies** [AustinDavies/MediatR.Behaviors.Authorization#15]
Currently, there are no unit tests to ensure functionality. Please let me know if anyone has time to create these tests. Any help would be appreciated.

**Comment by fernandoareias** [comment]
Hello @AustinDavies, I can work that, has any requirement?

**Comment by AustinDavies** [comment]
Mostly, that the core functionality works and requirements, both scoped and global, are registered and executed appropriately.

Thanks for wanting to pick this up!

**Comment by AustinDavies** [comment]
I will try to review your PR soon. Sorry for the delay.

**Comment by AustinDavies** [comment]
Looks great!
