### ISSUE TITLE
Upgrade MediatR version to 12.1.1

### ISSUE THREAD

**Issue by AustinDavies** [AustinDavies/MediatR.Behaviors.Authorization#17]
Upgrade MediatR version to 12.1.1

**Comment by christianfosli** [comment]
Hi @AustinDavies :smile:
I'm waiting eagerly for this to be merged and released on NuGet, to update to the latest MediatR version in a client project.
Do you have a status update? Do you need any help testing the branch? 
Sorry for the noise :-)

**Comment by AustinDavies** [comment]
> Hi @AustinDavies 😄 I'm waiting eagerly for this to be merged and released on NuGet, to update to the latest MediatR version in a client project. Do you have a status update? Do you need any help testing the branch? Sorry for the noise :-)

Hi, @christianfosli. Yes, I was waiting on testing this new version as it seems there may be some breaking changes according to the MediatR upgrade docs. Just want to make sure it won't break any existing functionality.

_Sorry for the noise :-)_ - No issues, it reminds me I have efforts to complete :-)
