### ISSUE TITLE
Behavior Handler calling _mediator.Send(requirement) issue

### ISSUE THREAD

**Issue by ge022** [AustinDavies/MediatR.Behaviors.Authorization#2]
_mediator.Send(requirement) is sending the requirement through all the pipelines, including through the authorization pipeline itself. Is there way to prevent this from happening?

**Comment by AustinDavies** [comment]
I am afraid there is not. This does bring up a good point though. I will look into modifying the design of this behavior to accommodate this issue.

**Comment by AustinDavies** [comment]
> _mediator.Send(requirement) is sending the requirement through all the pipelines, including through the authorization pipeline itself. Is there way to prevent this from happening?

I Have updated the behavior so that the requirement will not be sent through all pipelines. I.e., I removed the call to _mediator.Send().
