### ISSUE TITLE
IRequestPreProcessor versus IPipelineBehavior

### ISSUE THREAD

**Issue by samuelmaxton** [AustinDavies/MediatR.Behaviors.Authorization#4]
Hi there! This is a question. I'm busy implementing resource authorization in my clean architected solution and ran across your work.

My main question is why implement `IPipelineBehavior `instead of `IRequestPreProcessor`? My understanding is that `IRequestPreProcessor `is guaranteed to take place before Mediatr's Handler is called and the same cannot be said for `IPipelineBehavior`?

Thanks

**Comment by AustinDavies** [comment]
> Hi there! This is a question. I'm busy implementing resource authorization in my clean architected solution and ran across your work.
> 
> My main question is why implement `IPipelineBehavior `instead of `IRequestPreProcessor`? My understanding is that `IRequestPreProcessor `is guaranteed to take place before Mediatr's Handler is called and the same cannot be said for `IPipelineBehavior`?
> 
> Thanks

The `IRequestPreProcessor` at its heart is just a convenience interface that leverages a `IPipelineBehavior`. Only difference is that with `IRequestPreProcessor` you automatically register all implentations when you call .AddMediatR() during startup. This is important to remember when ordering your MediatR pipeline. So, what this means is, you can register a `IPipelineBehavior` before the call to . AddMediatR() and have that `IPipelineBehavior` execute BEFORE any implementations of `IRequestPreProcessor`.

However, I think you bring up a valid concern. I will add a section in the documentation about ordering to ensure this library's pipeline behavior executes first (if such ordering is desired for that specific application).
